### ISSUE TITLE
Updated utilized JDK version to at least 11

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-broker-image#16]
**Is your feature request related to a problem? Please describe.**
Prior to and since the base broker container image was first made available a number or progressive JDK updates have happened. At the moment the base is utilizing the now older v8 JDK while the JDK development has since moved on to 11 through 17 at least.

**Describe the solution you'd like**
At a minimum the configuration and utilization of the v8 JDK should be retired, with a new minimum of 11 being introduced depending on platform availability. Ideally a move to v17 could be made, however that may not be universally available across all platforms.

**Comment by brusdev** [comment]
The ubi8/openjdk-17-runtime container image used as base image doesn't include required JDK diagnostic tools so we need to change the base image to ubi8/openjdk-17.
